
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.Object;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templatesf
 * and open the template in the editor.
 */
/**
 *
 * @author beemo
 */
public class UseCasePoints extends javax.swing.JFrame {

    /**
     * Creates new form TaxCalculatorGUI
     */
    
    //usecase
    ArrayList<UseCase> usecaselist = new ArrayList<>();
    int total = 0;
    int totalSimple = 0;
    int totalAverage = 0;
    int totalAdvanced = 0;
    int uucw = 0;
    //actor
    ArrayList<Actor> actorlist = new ArrayList<>();
    int totalActor = 0;
    int totalSimpleActor = 0;
    int totalAverageActor = 0;
    int totalAdvancedActor = 0;
    int uaw = 0;   
    public UseCasePoints() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Complexity = new javax.swing.ButtonGroup();
        ActorComplexity = new javax.swing.ButtonGroup();
        nameTF = new javax.swing.JTextField();
        SimpleRB = new javax.swing.JRadioButton();
        AverageRB = new javax.swing.JRadioButton();
        ComplexRB = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calculateButton = new javax.swing.JButton();
        uucwLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTF1 = new javax.swing.JTextField();
        SimpleActorRB = new javax.swing.JRadioButton();
        AverageActorRB = new javax.swing.JRadioButton();
        ComplexActorRB = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        calculateButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        uawLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Complexity.add(SimpleRB);
        SimpleRB.setText("Simple");
        SimpleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleRBActionPerformed(evt);
            }
        });

        Complexity.add(AverageRB);
        AverageRB.setText("Average");
        AverageRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AverageRBActionPerformed(evt);
            }
        });

        Complexity.add(ComplexRB);
        ComplexRB.setText("Complex");
        ComplexRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplexRBActionPerformed(evt);
            }
        });

        jLabel1.setText("Use Case Name");

        jLabel2.setText("Complexity");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Difficulty", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        uucwLabel.setText("0");

        jLabel4.setText("Unadjusted Use Case Weight = ");

        ActorComplexity.add(SimpleActorRB);
        SimpleActorRB.setText("Simple");
        SimpleActorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpleActorRBActionPerformed(evt);
            }
        });

        ActorComplexity.add(AverageActorRB);
        AverageActorRB.setText("Average");
        AverageActorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AverageActorRBActionPerformed(evt);
            }
        });

        ActorComplexity.add(ComplexActorRB);
        ComplexActorRB.setText("Complex");
        ComplexActorRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComplexActorRBActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Difficulty", "Weight"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jScrollPane2.setViewportView(jTable2);

        calculateButton1.setText("Calculate");
        calculateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Actor Name");

        jLabel5.setText("Complexity");

        uawLabel.setText("0");

        jLabel6.setText("Unadjusted Actor Weight = ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uucwLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2))
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SimpleRB)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ComplexRB)
                                                .addComponent(AverageRB))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                            .addComponent(calculateButton))))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uawLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(nameTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SimpleActorRB)
                                        .addComponent(ComplexActorRB)
                                        .addComponent(AverageActorRB))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(calculateButton1))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SimpleRB)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AverageRB)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ComplexRB))
                        .addComponent(calculateButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uucwLabel)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SimpleActorRB)
                            .addComponent(nameTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AverageActorRB)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComplexActorRB)
                            .addComponent(calculateButton1)))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uawLabel)
                    .addComponent(jLabel6))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpleRBActionPerformed

    private void AverageRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AverageRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AverageRBActionPerformed

    private void ComplexRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplexRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComplexRBActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try {
            String name = nameTF.getText();
            int complexity = 0;
            //String status;
            final int SIMPLE = 5;
            final int AVERAGE = 10;
            final int COMPLEX = 15;
            String difficulty = "";
            if (SimpleRB.isSelected()) {
                difficulty = "Simple";
                complexity = SIMPLE; 
                totalSimple++;
            } else if (AverageRB.isSelected()) {
                complexity = AVERAGE;
                difficulty = "Average";
                totalAverage++;

            } else if (ComplexRB.isSelected()) {
                complexity = COMPLEX;
                difficulty = "Complex";
                totalAdvanced++;
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Specify your element complexity!");
            }
            UseCase usecase = new UseCase(name,complexity);
            usecaselist.add(usecase);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{usecase.getName(),difficulty,complexity});
            uucw = (totalSimple * 5) + (totalAverage * 10) + (totalAdvanced * 15);
            uucwLabel.setText(Integer.toString(uucw));    

        
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "please Fill All the fields with the appropriate Data!!");
        }
        catch (ArrayIndexOutOfBoundsException oob){
            JOptionPane.showMessageDialog(null, "Reached End Of Array Size!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void SimpleActorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpleActorRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpleActorRBActionPerformed

    private void AverageActorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AverageActorRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AverageActorRBActionPerformed

    private void ComplexActorRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComplexActorRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComplexActorRBActionPerformed

    private void calculateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButton1ActionPerformed
          try {
            String name = nameTF.getText();
            int complexity = 0;
            //String status;
            final int SIMPLE = 1;
            final int AVERAGE = 2;
            final int COMPLEX = 3;
            String difficulty = "";
            if (SimpleActorRB.isSelected()) {
                difficulty = "Simple";
                complexity = SIMPLE; 
                totalSimpleActor++;
            } else if (AverageActorRB.isSelected()) {
                complexity = AVERAGE;
                difficulty = "Average";
                totalAverageActor++;

            } else if (ComplexActorRB.isSelected()) {
                complexity = COMPLEX;
                difficulty = "Complex";
                totalAdvancedActor++;
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Specify your element complexity!");
            }
            Actor actor = new Actor(name,complexity);
            actorlist.add(actor);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.addRow(new Object[]{actor.getName(),difficulty,complexity});
            uaw = (totalSimpleActor * 1) + (totalAverageActor * 2) + (totalAdvancedActor * 3);
            uawLabel.setText(Integer.toString(uaw));   

        
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "please Fill All the fields with the appropriate Data!!");
        }
        catch (ArrayIndexOutOfBoundsException oob){
            JOptionPane.showMessageDialog(null, "Reached End Of Array Size!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_calculateButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UseCasePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UseCasePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UseCasePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UseCasePoints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UseCasePoints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ActorComplexity;
    private javax.swing.JRadioButton AverageActorRB;
    private javax.swing.JRadioButton AverageRB;
    private javax.swing.JRadioButton ComplexActorRB;
    private javax.swing.JRadioButton ComplexRB;
    private javax.swing.ButtonGroup Complexity;
    private javax.swing.JRadioButton SimpleActorRB;
    private javax.swing.JRadioButton SimpleRB;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton calculateButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField nameTF1;
    private javax.swing.JLabel uawLabel;
    private javax.swing.JLabel uucwLabel;
    // End of variables declaration//GEN-END:variables
}
